//
//  Teams.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.13
//

import Foundation
import UIKit
import AWSDynamoDB

class Teams: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _team: String?
    var _userId: String?
    var _username: String?
    
    class func dynamoDBTableName() -> String {
        
        return "jogarun-mobilehub-2062646821-teams"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_team"
    }
    
    class func rangeKeyAttribute() -> String {
        
        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_team" : "team",
            "_userId" : "userId",
            "_username" : "username",
        ]
    }
}
