//
//  UserPoolMFAViewController.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//
//

import Foundation
import AWSMobileHubHelper
import AWSCognitoIdentityProvider

class UserPoolMFAViewController: UIViewController {
    
    var destination: String?
    var mfaCodeCompletionSource: AWSTaskCompletionSource<NSString>?
    
    @IBOutlet weak var codeSentTo: UILabel!
    @IBOutlet weak var authenticationCode: UITextField!
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.codeSentTo.text = self.destination
        self.authenticationCode.text = nil
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // perform any action, if required, once the view is loaded
    }
    
    @IBAction func onSignIn(_ sender: AnyObject) {
        // check if the user is not providing an empty authentication code 
        guard let authenticationCodeValue = self.authenticationCode.text, !authenticationCodeValue.isEmpty else {
            UIAlertView(title: "Authentication Code Missing",
                        message: "Please enter the authentication code you received by E-mail / SMS.",
                        delegate: nil,
                        cancelButtonTitle: "Ok").show()
            return
        }
        self.mfaCodeCompletionSource?.set(result: authenticationCodeValue as NSString)
    }
    
    @IBAction func onCancel(_ sender: AnyObject) {
        _ = self.navigationController?.popToRootViewController(animated: true)
    }
}

extension UserPoolMFAViewController : AWSCognitoIdentityMultiFactorAuthentication {
    
    func didCompleteMultifactorAuthenticationStepWithError(_ error: Error?) {
        if let localError = error as? NSError {
            DispatchQueue.main.async(execute: {
                UIAlertView(title: localError.userInfo["__type"] as? String,
                    message: localError.userInfo["message"] as? String,
                    delegate: nil,
                    cancelButtonTitle: nil).show()
            })
        }
    }
    
    func getCode(_ authenticationInput: AWSCognitoIdentityMultifactorAuthenticationInput, mfaCodeCompletionSource: AWSTaskCompletionSource<NSString>) {
        self.mfaCodeCompletionSource = mfaCodeCompletionSource
        self.destination = authenticationInput.destination
    }
    
}
